


```{r, message = FALSE}

library(tidyverse)


is.scalar.na <- function(x) {
  all(is.na(x)) & length(x) == 1
}

is.scalar.null <- function(x) {
  all(is.null(x)) & length(x) == 0
}

is.scalar.na.or.null <- function(x) {
  is.scalar.na(x) | is.scalar.null(x)
}


```


```{r}

test_pars <- readxl::read_excel('test_parameters.xlsx')

```


```{r}

sort_mel_nos <- function(df) {
  df %>% 
    pull(`BERKOWITZ MELODIES`) %>% 
    purrr::map(~strsplit(.x, split = ",")) %>% 
    unlist() %>% 
    as.integer()
}

```


```{r}

group_1 <- test_pars %>% 
  slice(1:3)  %>% 
  sort_mel_nos() %>% 
  tibble::tibble(stimulus = ., 
                 melody_group = "1")

group_2 <- test_pars %>% 
  slice(4:6)  %>% 
  sort_mel_nos() %>% 
  tibble::tibble(stimulus = ., 
                 melody_group = "2")



group_3 <- test_pars %>% 
  slice(7:8)  %>% 
  sort_mel_nos() %>% 
  tibble::tibble(stimulus = ., 
                 melody_group = "3")


group_4 <- test_pars %>% 
  slice(9:10)  %>% 
  sort_mel_nos()  %>% 
  tibble::tibble(stimulus = ., 
                 melody_group = "4")


```


```{r}

suzuki_item_bank <- rbind(group_1, group_2, group_3, group_4) %>% 
  relocate(melody_group) %>% 
  na.omit %>% 
  dplyr::rowwise() %>% 
  mutate(file_key = paste0("Berkowitz", stimulus)) %>% 
  ungroup()


```


```{r}

suzuki_item_bank_ngram <- suzuki_item_bank

suzuki_item_bank_phrase <- suzuki_item_bank

suzuki_item_bank <-  suzuki_item_bank %>% 
  left_join(Berkowitz::item_item_bank, by = "file_key")


suzuki_item_bank_ngram <- suzuki_item_bank_ngram %>% 
  rowwise() %>% 
  mutate(midi_file = paste0(file_key, ".mid")) %>% 
  ungroup() %>% 
  left_join(Berkowitz::ngram_item_bank, by = "midi_file")


suzuki_item_bank_phrase <- suzuki_item_bank_phrase %>% 
  rowwise() %>% 
  mutate(midi_file = paste0(file_key, ".mid")) %>% 
  ungroup() %>% 
  left_join(Berkowitz::phrase_item_bank, by = "midi_file") %>% 
  filter(N %in% 3:15)

```



```{r}

suzuki_item_bank %>% 
  writexl::write_xlsx('suzuki_item_bank.xlsx')

suzuki_item_bank_ngram %>% 
  writexl::write_xlsx('suzuki_item_bank_ngram.xlsx')

suzuki_item_bank_phrase %>% 
  writexl::write_xlsx('suzuki_item_bank_phrase.xlsx')

```


Check features

```{r}

suzuki_item_bank %>% 
  select(melody_group, mean_int_size, N, tonalness) %>% 
  pivot_longer(mean_int_size:tonalness, names_to = "Feature", values_to = "Value") %>% 
  rename(`Melody Group` = melody_group) %>% 
    ggplot(aes(x = Feature, y = Value, fill = `Melody Group`, group = `Melody Group`)) +
      geom_bar(position = "dodge", stat = "summary", fun = "mean") +
      facet_wrap(~Feature, scales = "free") +
      theme_minimal()


```


```{r}

suzuki_item_bank_ngram %>% 
  select(melody_group, mean_int_size, N, tonalness) %>% 
  pivot_longer(mean_int_size:tonalness, names_to = "Feature", values_to = "Value") %>% 
  rename(`Melody Group` = melody_group) %>% 
    ggplot(aes(x = Feature, y = Value, fill = `Melody Group`, group = `Melody Group`)) +
      geom_bar(position = "dodge", stat = "summary", fun = "mean") +
      facet_wrap(~Feature, scales = "free") +
      theme_minimal()


```

```{r}

suzuki_item_bank_phrase %>% 
  select(melody_group, mean_int_size, N, tonalness) %>% 
  pivot_longer(mean_int_size:tonalness, names_to = "Feature", values_to = "Value") %>% 
  rename(`Melody Group` = melody_group) %>% 
    ggplot(aes(x = Feature, y = Value, fill = `Melody Group`, group = `Melody Group`)) +
      geom_bar(position = "dodge", stat = "summary", fun = "mean") +
      facet_wrap(~Feature, scales = "free") +
      theme_minimal()


```





Clare's selection

We get the phrase and ngram sets separately so we can join the items on



```{r}

suzuki_phrase <- readxl::read_excel('Berk Final Vn Vla Cello 11April.xlsx') %>% 
  dplyr::filter(grepl("phrase", item_id)) %>% 
  dplyr::left_join(suzuki_item_bank_phrase, by = "item_id") 

```



```{r}

suzuki_ngram <- readxl::read_excel('Berk Final Vn Vla Cello 11April.xlsx') %>% 
  filter(grepl("ngram", item_id)) %>% 
  left_join(suzuki_item_bank_ngram, by = "item_id") 

```

```{r}

joint_names <- intersect(names(suzuki_phrase), names(suzuki_ngram))

suzuki_selected_item_bank <- rbind(
  suzuki_phrase %>% select(all_of(joint_names)),
  suzuki_ngram %>% select(all_of(joint_names))
) %>% # NB. For now remove NA vals
  na.omit

```




Add difficulties

```{r, message = FALSE, warning = FALSE}


phrase_arrhythmic_difficulty <- predict(Berkowitz::lm2.2,
                      newdata = suzuki_selected_item_bank %>% mutate(log_freq = 0),
                      re.form = NA) %>% # this instructs the model to predict without random effects )
                      as.numeric %>%
                      magrittr::multiply_by(-1) %>%
                      scales::rescale()

phrase_rhythmic_difficulty <- predict(Berkowitz::lm3.2,
                                 newdata = suzuki_selected_item_bank %>% mutate(log_freq = 0),
                                 re.form = NA)


suzuki_selected_item_bank <- suzuki_selected_item_bank %>% 
  mutate(arrhythmic_difficulty = phrase_arrhythmic_difficulty,
         rhythmic_difficulty = phrase_rhythmic_difficulty) 

```




Put in keys: G, D, A for violin; C, G, D for viola/cello

We work out the key based on the *full* melody

```{r}

berkowitz_keys <- Berkowitz::item_item_bank %>% 
  dplyr::as_tibble() %>% 
  select(abs_melody, file_key) %>%
  rowwise() %>% 
  mutate(key = musicassessr::get_implicit_harmonies( itembankr::str_mel_to_vector(abs_melody) )$key ) %>% 
  ungroup()


use_data(berkowitz_keys)

```


```{r}

suzuki_selected_item_bank <- suzuki_selected_item_bank %>% 
  left_join(berkowitz_keys %>% select(file_key, key), by = "file_key") 


```


```{r}

suzuki_selected_item_bank <- suzuki_selected_item_bank %>% 
  rowwise() %>% 
  mutate(
         first_note = itembankr::str_mel_to_vector(abs_melody)[1],
         lowest_note = min(itembankr::str_mel_to_vector(abs_melody), na.rm = TRUE),
         highest_note = max(itembankr::str_mel_to_vector(abs_melody), na.rm = TRUE)
         ) %>% 
  ungroup()

```


```{r}

suzuki_selected_item_bank_violin <- suzuki_selected_item_bank %>% 
  mutate(instrument = "Violin") %>% 
  rowwise() %>% 
  mutate(abs_melody = if(lowest_note < 55) paste0(itembankr::str_mel_to_vector(abs_melody) + 12, collapse = ",") else  abs_melody,
         prompt = paste0("The starting note is ", `Vn start note`, " and finger number is ", `Violin finger/string`, ".") ) %>% 

  ungroup()

```

```{r}

suzuki_selected_item_bank_cello <- suzuki_selected_item_bank %>% 
  mutate(instrument = "Cello",
         abs_melody = case_when(highest_note > 72 ~ paste0(itembankr::str_mel_to_vector(abs_melody) - 12, collapse = ","), TRUE ~ abs_melody ),
         prompt = paste0("The starting note is ", `Cello start note`, " and finger number is ", `Cello finger/string`, ".") ) %>% 
  ungroup()

```






Check opti3

-- Violin

```{r}


suzuki_selected_item_bank_violin <- suzuki_selected_item_bank_violin %>% 
  dplyr::rowwise() %>% 
  dplyr::mutate(
    pyin = list(pyin::pyin(paste0(
    system.file('Berk_Cut_melodies_violin_noclick', package = 'ClarePBETBattery2024'), "/", `Violin Audio File name`))),
    opti3 = if(is.scalar.na.or.null(unlist(pyin))) NA else musicassessr::get_opti3(stimuli = itembankr::str_mel_to_vector(abs_melody), 
                      stimuli_durations = itembankr::str_mel_to_vector(durations), 
                      stimuli_length = N, user_input_as_pyin = pyin, segment_phrase = FALSE)) %>% 
  ungroup()


```

```{r}


apply_ed <- function(melody, pyin_df) {
  
    if(is.scalar.na.or.null(pyin_df)) {
    return(NA)
  }
  
  
  transcribed_intervals <- paste0(diff(pyin_df$note), collapse = ",")


  edit_sim(melody, transcribed_intervals)

}


suzuki_selected_item_bank_violin <- suzuki_selected_item_bank_violin %>% 
  rowwise() %>% 
  mutate(
    int_edit_dist = apply_ed(melody, pyin) 
    ) %>% 
  dplyr::ungroup()


```


```{r}


apply_ngrukkon2 <- function(melody, pyin_df) {
  
  if(is.scalar.na.or.null(pyin_df)) {
    return(NA)
  }
  
  
 musicassessr::ngrukkon(x = itembankr::str_mel_to_vector(melody), y = diff(pyin_df$note), N = 2)
 
}

apply_ngrukkon2_dur_weighted <- function(melody, durations, pyin_df) {
  
  if(is.scalar.na.or.null(pyin_df)) {
    return(NA)
  }
  
  browser()
  
 musicassessr::ngrukkon(x = itembankr::str_mel_to_vector(melody), y = diff(pyin_df$note), N = 2)
 
}

# ngrukkon


suzuki_selected_item_bank_violin <- suzuki_selected_item_bank_violin %>% 
  rowwise() %>% 
  mutate(
    #ngrukkon2 = apply_ngrukkon2(melody, pyin)
    ngrukkon2_dur_weighted = apply_ngrukkon2_dur_weighted(melody, durations, pyin)
    ) %>% 
  dplyr::ungroup()


```


```{r}





edit_dist <- function(s, t){
  adist(s,t)[1,1]
}

edit_sim <- function(s, t){
  1 - edit_dist(s, t)/max(nchar(s), nchar(t))
}


v1 <- c(3, 3, 4, -2, -2, -1, 3, -7)

v2 <- c(3, 3, 4, 0, 0, -2, -2, -1, 3, -7)



edit_sim(paste0(v1, collapse = ","), paste0(v2, collapse = ","))

```

```{r}


edit_dist(intToUtf8(v1), intToUtf8(v2))



```


```{r}

mean(suzuki_selected_item_bank_violin$int_edit_dist, na.rm = TRUE)

mean(suzuki_selected_item_bank_violin$ngrukkon2, na.rm = TRUE)

```


```{r}

problem_violin <- suzuki_selected_item_bank_violin %>% 
  unnest_wider(opti3) %>% 
  filter(!near(ngrukkon, 1) | is.na(ngrukkon)) %>% 
  arrange(ngrukkon)

```


```{r}

avg_ngrukkon <- mean(problem_violin$ngrukkon, na.rm = TRUE)

avg_ngrukkon

# 0.482089

```


```{r}


problem_violin <- problem_violin %>% 
  dplyr::rowwise() %>% 
  dplyr::mutate(
    pyin2 = list(pyin::pyin(paste0(
    system.file('Berk_Cut_melodies_violin_noclick', package = 'ClarePBETBattery2024'), "/", `Violin Audio File name`), normalise = TRUE,
    transform_file = "~/ClarePBETBattery2024/pyin_par_skel_optimised.ttl"
    )),
    opti3_2 = if(is.scalar.na.or.null(unlist(pyin2))) NA else musicassessr::get_opti3(stimuli = itembankr::str_mel_to_vector(abs_melody), 
                      stimuli_durations = itembankr::str_mel_to_vector(durations), 
                      stimuli_length = N, user_input_as_pyin = pyin2, segment_phrase = FALSE)
    ) %>% 
  dplyr::ungroup()

```



```{r}

problem_violin <- problem_violin %>% 
  select(-c(transposition, ngrukkon, rhythfuzz, harmcore, opti3)) %>% 
  unnest_wider(opti3_2) %>% 
  filter(!near(ngrukkon, 1) | is.na(ngrukkon)) %>% 
  arrange(ngrukkon)

```

```{r}

problem_violin <- problem_violin %>% 
  filter(!near(ngrukkon, 1) | is.na(ngrukkon)) %>% 
  arrange(ngrukkon)

```

```{r}

avg_ngrukkon <- mean(problem_violin$ngrukkon, na.rm = TRUE)

avg_ngrukkon

```



```{r}

hist(suzuki_selected_item_bank_violin$opti3$ngrukkon)

```

```{r}


suzuki_selected_item_bank_violin %>% 
  unnest_wider(opti3) %>% 
  select(item_id, ngrukkon) %>% 
  writexl::write_xlsx('clare_opti3_check_violin.xlsx')

```



-- Cello

```{r}

suzuki_selected_item_bank_cello <- suzuki_selected_item_bank_cello %>% 
  dplyr::rowwise() %>% 
  dplyr::mutate(
    pyin = list(pyin::pyin(paste0(
    system.file('Berk_Cut_melodies_cello_noclick', package = 'ClarePBETBattery2024'), "/", `Cello Audio File Name`))),
    opti3 = if(is.scalar.na.or.null(unlist(pyin))) NA else musicassessr::get_opti3(stimuli = itembankr::str_mel_to_vector(abs_melody), 
                      stimuli_durations = itembankr::str_mel_to_vector(durations), 
                      stimuli_length = N, user_input_as_pyin = pyin, segment_phrase = FALSE)
    ) %>% 
  dplyr::ungroup()



```



```{r}

hist(suzuki_selected_item_bank_violin$opti3$ngrukkon)

```

```{r}


suzuki_selected_item_bank_violin %>% 
  unnest_wider(opti3) %>% 
  select(item_id, ngrukkon) %>% 
  writexl::write_xlsx('clare_opti3_check_violin.xlsx')

```





```{r}

use_data(suzuki_selected_item_bank, suzuki_selected_item_bank_violin, suzuki_selected_item_bank_cello, overwrite = TRUE)

```








